...

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -29,8 +29,8 @@ am__make_running_with_option = \
   case $${target_option-} in \
       ?) ;; \
       *) echo "am__make_running_with_option: internal error: invalid" \
-              "target option '$${target_option-}' specified" >&2; \
-         exit 1;; \
+	      "target option '$${target_option-}' specified" >&2; \
+	 exit 1;; \
   esac; \
   has_opt=no; \
   sane_makeflags=$$MAKEFLAGS; \
@@ -39,9 +39,9 @@ am__make_running_with_option = \
   else \
     case $$MAKEFLAGS in \
       *\\[\ \	]*) \
-        bs=\\; \
-        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
-          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
+	bs=\\; \
+	sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
+	  | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
     esac; \
   fi; \
   skip_next=no; \
@@ -53,11 +53,11 @@ am__make_running_with_option = \
     test $$skip_next = yes && { skip_next=no; continue; }; \
     case $$flg in \
       *=*|--*) continue;; \
-        -*I) strip_trailopt 'I'; skip_next=yes;; \
+	-*I) strip_trailopt 'I'; skip_next=yes;; \
       -*I?*) strip_trailopt 'I';; \
-        -*O) strip_trailopt 'O'; skip_next=yes;; \
+	-*O) strip_trailopt 'O'; skip_next=yes;; \
       -*O?*) strip_trailopt 'O';; \
-        -*l) strip_trailopt 'l'; skip_next=yes;; \
+	-*l) strip_trailopt 'l'; skip_next=yes;; \
       -*l?*) strip_trailopt 'l';; \
       -[dEDm]) skip_next=yes;; \
       -[JT]) skip_next=yes;; \
@@ -449,7 +449,7 @@ am__uninstall_files_from_dir = { \
   test -z "$$files" \
     || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
     || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
-         $(am__cd) "$$dir" && rm -f $$files; }; \
+	 $(am__cd) "$$dir" && rm -f $$files; }; \
   }
 am__recheck_rx = ^[ 	]*:recheck:[ 	]*
 am__global_test_result_rx = ^[ 	]*:global-test-result:[ 	]*
@@ -462,20 +462,20 @@ am__list_recheck_tests = $(AWK) '{ \
   while ((rc = (getline line < ($$0 ".trs"))) != 0) \
     { \
       if (rc < 0) \
-        { \
-          if ((getline line2 < ($$0 ".log")) < 0) \
+	{ \
+	  if ((getline line2 < ($$0 ".log")) < 0) \
 	    recheck = 0; \
-          break; \
-        } \
+	  break; \
+	} \
       else if (line ~ /$(am__recheck_rx)[nN][Oo]/) \
-        { \
-          recheck = 0; \
-          break; \
-        } \
+	{ \
+	  recheck = 0; \
+	  break; \
+	} \
       else if (line ~ /$(am__recheck_rx)[yY][eE][sS]/) \
-        { \
-          break; \
-        } \
+	{ \
+	  break; \
+	} \
     }; \
   if (recheck) \
     print $$0; \
@@ -504,24 +504,24 @@ function rst_section(header) \
   while ((rc = (getline line < ($$0 ".trs"))) != 0) \
     { \
       if (rc < 0) \
-         fatal("failed to read from " $$0 ".trs"); \
+	 fatal("failed to read from " $$0 ".trs"); \
       if (line ~ /$(am__global_test_result_rx)/) \
-        { \
-          sub("$(am__global_test_result_rx)", "", line); \
-          sub("[ 	]*$$", "", line); \
-          global_test_result = line; \
-        } \
+	{ \
+	  sub("$(am__global_test_result_rx)", "", line); \
+	  sub("[ 	]*$$", "", line); \
+	  global_test_result = line; \
+	} \
       else if (line ~ /$(am__copy_in_global_log_rx)[nN][oO]/) \
-        copy_in_global_log = 0; \
+	copy_in_global_log = 0; \
     }; \
   if (copy_in_global_log) \
     { \
       rst_section(global_test_result ": " $$0); \
       while ((rc = (getline line < ($$0 ".log"))) != 0) \
       { \
-        if (rc < 0) \
-          fatal("failed to read from " $$0 ".log"); \
-        print line; \
+	if (rc < 0) \
+	  fatal("failed to read from " $$0 ".log"); \
+	print line; \
       }; \
       printf "\n"; \
     }; \
@@ -594,8 +594,8 @@ am__set_b = \
   case '$@' in \
     */*) \
       case '$*' in \
-        */*) b='$*';; \
-          *) b=`echo '$@' | sed 's/\.log$$//'`; \
+	*/*) b='$*';; \
+	  *) b=`echo '$@' | sed 's/\.log$$//'`; \
        esac;; \
     *) \
       b='$*';; \
@@ -819,19 +819,19 @@ EXTRA_DIST = tap-driver.sh test_tps_splitcomm.py soln_differ inputs meshes lte-d
 	          ref_solns/*.h5 ref_solns/collisions/*.h5 ref_solns/transport/*.h5 \
 			  ref_solns/reaction/*.h5 ref_solns/noSGM1K/*.h5 ref_solns/smag1K_1/*.h5 \
 			  ref_solns/sigma1K_1/*.h5 ref_solns/plate150K/*.h5 ref_solns/plate150K_1step/*.h5 \
-              ref_solns/heatedBox/*.h5 ref_solns/spongeBox/*.h5 ref_solns/interpInlet/*.h5 \
-              ref_solns/sgsLoMach/*.h5 \
+	      ref_solns/heatedBox/*.h5 ref_solns/spongeBox/*.h5 ref_solns/interpInlet/*.h5 \
+	      ref_solns/sgsLoMach/*.h5 \
 	      ref_solns/lequere-varmu/*.h5 \
 	      ref_solns/taylor-couette/*.h5 \
 	      ref_solns/pipe/*.h5 \
 	      ref_solns/aveLoMach/*.h5 \
-              ref_solns/reactBinDiff/*.h5 \
-              ref_solns/reactSingleRx/*.h5 \
-              ref_solns/reactTable/*.h5 \
-              ref_solns/stabChan/*.h5 \
-              ref_solns/radDecay/*.h5 \
-              ref_solns/reactNitrogen/*.h5 \
-              ref_solns/supg/*.h5 \
+	      ref_solns/reactBinDiff/*.h5 \
+	      ref_solns/reactSingleRx/*.h5 \
+	      ref_solns/reactTable/*.h5 \
+	      ref_solns/stabChan/*.h5 \
+	      ref_solns/radDecay/*.h5 \
+	      ref_solns/reactNitrogen/*.h5 \
+	      ref_solns/supg/*.h5 \
 			  ref_solns/pipe.zeta-f/*.h5 \
 		      vpath.sh die.sh count_gpus.sh sniff_mpirun.sh \
 		      cyl3d.gpu.test cyl3d.mflow.gpu.test wedge.gpu.test \
@@ -839,16 +839,16 @@ EXTRA_DIST = tap-driver.sh test_tps_splitcomm.py soln_differ inputs meshes lte-d
 		      die.test averaging.test wedge.test cyl3d.interp.test qms.rings.test qms.axisym.test \
 		      sponge_zone.test annulus.test pipe.test valgrind.test valgrind.suppressions \
 		      mms.euler.test reaction.test perfect_gas.test collision_integrals.test \
-                      diffusion_wall.test \
+	              diffusion_wall.test \
 	 	      inflow_outflow.test mms.ternary_2d.test mms.ternary_2d_wall.test \
 	 	      mms.ternary_2d_inout.test cuda-memcheck.test mms.general_wall.test \
 		      independent_coupling.test interp_em.test mms.euler_2d.test mms.cns_2d.test \
 		      gradient.test coupled-3d.test coupled-3d.splitcomm.test coupled-3d.py-loop.test \
 		      tabulated.test lte_mixture.test distance_fcn.test \
-              sgsSmag.test sgsSigma.test heatEq.test sponge.test plate.test pipe.mix.test lte2noneq-restart.test \
-              coupled-3d.interface.test plasma.axisym.test plasma.axisym.lte1d.test \
+	      sgsSmag.test sgsSigma.test heatEq.test sponge.test plate.test pipe.mix.test lte2noneq-restart.test \
+	      coupled-3d.interface.test plasma.axisym.test plasma.axisym.lte1d.test \
 	      	  lomach-flow.test lomach-lequere.test interpInlet.test sgsLoMach.test autoPeriodic.test aveLoMach.test \
-              reactFlow-binDiff.test reactFlow-singleRx.test reactFlow-table.test radiativeDecay.test \
+	      reactFlow-binDiff.test reactFlow-singleRx.test reactFlow-table.test radiativeDecay.test \
 			  reactFlow-nitrogen.test argon_minimal.test argon_minimal.binary.test \
 			  supg-scalars.test lomach-pipe-zf.test
 
